name = "SpirvCross"
uuid = "f06137f4-7fbd-40d2-9445-4d828b4624cb"
authors = ["Cédric Belmant"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
